### ISSUE TITLE
[24pt] Create Movie Class [Lawrence Kioko]

### ISSUE THREAD

**Issue by sergio-usma** [sergio-usma/Ruby-capstone-project#5]
- [x] #15
- [x] #16
- [x] #17
- [x] #22
- [x] #23
- [x] add_item method in the Source class
- [x] should take an instance of the Item class as an input
- [x] should add the input item to the collection of items
- [x] should add self as a property of the item object (by using the correct setter from the item object)
- [x] can_be_archived?() in the Movie class
- [x] should override the method from the parent class
- [x] should return true if parent's method returns true OR if silent equals true
- [x] otherwise, it should return false
- [x] #18
- [x] #19
- [x] List all movies
- [x] List all sources (e.g. 'From a friend', 'Online shop')
- [x] Add a movie
- [x] #20
- [x] #21
- [x] movies table (add all properties and associations from the parent Item class as table columns)
- [x] sources table

**Comment by Kidd254** [comment]
A link to the pull request https://github.com/sergio-usma/Ruby-capstone-project/pull/47
